[platformio]
extra_configs = private.ini

[env:arduino_nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino

upload_protocol = dfu
upload_port = USB

monitor_port = COM6
monitor_speed = 115200

build_flags =
    -DETH_SPI_SUPPORTS_CUSTOM=1

lib_deps =
    miguelbalboa/MFRC522
		khoih-prog/Ethernet_Generic
    bblanchon/ArduinoJson