[env:arduino_nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino

upload_protocol = dfu
upload_port = USB

monitor_port = COM6
monitor_speed = 115200

lib_deps =
    miguelbalboa/MFRC522